const Map<String, String> bn = {
  'appTitle': 'এডু ব্রিজ',
  'welcome': 'স্বাগতম!',
  'signIn': 'সাইন ইন',
  'signOut': 'সাইন আউট',
  'profile': 'প্রোফাইল',
  'home': 'হোম',
  'settings': 'সেটিংস',
  'dark_mode': 'ডার্ক মোড',
  'language': 'ভাষা',
  // Course UI
  'popular_courses': 'জনপ্রিয় কোর্স',
  'add_course_details': 'কোর্সের বিস্তারিত যোগ করুন',
  'add_course_type': 'কোর্সের ধরন যোগ করুন',
  'add_course_title': 'কোর্সের শিরোনাম যোগ করুন',
  'add_price': 'মূল্য যোগ করুন',
  'course_name_hint': 'কোর্সের নাম',
  'course_price_hint': 'কোর্সের মূল্য',
  'course_type_hint': 'কোর্সের ধরন',
  'add_image': 'ছবি যোগ করুন',
  'add': 'যোগ করুন',
  'error_fill_fields': 'সব ঘর পূরণ করুন এবং একটি ছবি যোগ করুন।',
  'price': 'মূল্য',
  // Banner UI
  'add_banner': 'ব্যানার যোগ করুন',
  'enter_banner_name': 'ব্যানারের নাম লিখুন',
  'no_image_selected': 'কোনো ছবি নির্বাচন করা হয়নি',
  'insert_banner_instruction': '৩৬০x১৮০ ব্যানার দিন',
  // Mentor UI
  'top_mentor': 'শ্রেষ্ঠ মেন্টর',
  'add_mentor_name': 'মেন্টরের নাম যোগ করুন',
  'add_mentor_info': 'মেন্টরের তথ্য যোগ করুন',
  'designation_hint': 'পদবী',
  'what_he_do_hint': 'তিনি কি করেন',
  'description_hint': 'বর্ণনা',
  'label_name': 'নাম',
  'label_designation': 'পদবী',
  'label_what_he_do': 'তিনি যা করেন',
  'label_description': 'বর্ণনা',
  // Bangla additions
  'user_email': 'ইউজার ইমেইল',
  'warning': 'সতর্কতা',
  // Other
  'add_class': 'ক্লাস যোগ করুন',
  'enter_class_name': 'ক্লাসের নাম লিখুন',
  'fill_your_profile': 'আপনার প্রোফাইল পূরণ করুন',
  'your_profile': 'তোমার প্রোফাইল',
  'popular_course': 'জনপ্রিয় কোর্স',
  'see_all': 'সব দেখুন',
  'forget_password': 'পাসওয়ার্ড ভুলে গেছেন',
  'categories': 'বিভাগসমূহ',
  'hi_there': 'হ্যালো!',
  'search_prompt': 'আজ আপনি কী শিখতে চান?\nনীচে অনুসন্ধান করুন',
  'no_content_available': 'কোনো কনটেন্ট উপলব্ধ নেই',
  'add_pin_number_security':
      'আপনার অ্যাকাউন্টকে আরও নিরাপদ করতে একটি পিন নম্বর যোগ করুন',
  'add_new_chapter': 'নতুন অধ্যায় যোগ করুন',
  'enter_chapter_name': 'অধ্যায়ের নাম লিখুন',
  'add_subject_name': 'বিষয়ের নাম যোগ করুন',
  'no_notes_yet': 'এখনও কোনো নোট নেই। উপরের দিকে একটি যোগ করুন!',
  'no_banners_available': 'কোনো ব্যানার উপলব্ধ নেই',
  'skip': 'এড়িয়ে যান',
  'get_started': 'শুরু করুন',
  'next': 'পরবর্তী',
  'select_language': 'ভাষা নির্বাচন করুন',
  'toggle_theme': 'থিম পরিবর্তন করুন',
  'education_for_everyone': 'সবাই জন্য শিক্ষা',
  'empowering_minds': 'মনের শক্তি, একটি উন্নত বাংলাদেশের নির্মাণ\nফ্রি শিখুন!',
  'learn_and_share': 'শিখুন এবং শেয়ার করুন',
  'learn_teach_inspire':
      'শিখুন, শেখান, এবং একসাথে অনুপ্রাণিত করুন, আমরা পরিবর্তন সৃষ্টি করি!',
  'transform_the_future': 'ভবিষ্যত রূপান্তর করুন',
  'knowledge_our_progress':
      'আপনার জ্ঞান, আমাদের অগ্রগতি, একটি নতুন বাংলাদেশের জন্য আকার!',
  'no_user_profile_found': 'কোনো ইউজার প্রোফাইল পাওয়া যায়নি',
  'about_user': 'ব্যবহারকারী সম্পর্কে',
  'notification': 'নোটিফিকেশন',
  'help_center': 'সাহায্য কেন্দ্র',
  'invite_friends': 'বন্ধুদের আমন্ত্রণ জানান',
};
