const Map<String, String> en = {
  'appTitle': 'EduBridge',
  'welcome': 'Welcome!',
  'signIn': 'Sign In',
  'signOut': 'Sign Out',
  'profile': 'Profile',
  'home': 'Home',
  'settings': 'Settings',
  'dark_mode': 'Dark Mode',
  'language': 'Language',
  // Course UI
  'popular_courses': 'Popular Courses',
  'add_course_details': 'Add Course Details',
  'add_course_type': 'Add Course Type',
  'add_course_title': 'Add Course Title',
  'add_price': 'Add Price',
  'course_name_hint': 'Course Name',
  'course_price_hint': 'Course Price',
  'course_type_hint': 'Course Type',
  'add_image': 'Add Image',
  'add': 'Add',
  'error_fill_fields': 'Please fill all fields and add an image.',
  'price': 'Price',
  // Banner UI
  'add_banner': 'Add Banner',
  'enter_banner_name': 'Enter banner name',
  'no_image_selected': 'No image selected',
  // Mentor UI
  'top_mentor': 'Top Mentor',
  'add_mentor_name': 'Add Mentor Name',
  'add_mentor_info': 'Add Mentor Information',
  'designation_hint': 'Designation',
  'what_he_do_hint': 'What he do',
  'description_hint': 'Description',
  // English additions
  'label_name': 'Name',
  'label_designation': 'Designation',
  'label_what_he_do': 'What He Do',
  'label_description': 'Description',
  'user_email': 'User Email',
  'warning': 'Warning',
  // Other
  'add_class': 'Add Class',
  'enter_class_name': 'Enter Class Name',
  'fill_your_profile': 'Fill Your Profile',
  'your_profile': 'Your Profile',
  'popular_course': 'Popular Course',
  'see_all': 'SEE ALL',
  'forget_password': 'Forget Password',
  'categories': 'Categories',
  'hi_there': 'Hi there!',
  'search_prompt': 'What would you like to learn today? \nSearch below',
  'no_content_available': 'No content available',
  'add_pin_number_security':
      'Add a Pin Number to Make Your Account\n more Secure',
  'add_new_chapter': 'Add New Chapter',
  'enter_chapter_name': 'Enter Chapter Name',
  'add_subject_name': 'Add Subject Name',
  'no_notes_yet': 'No notes yet. Add one above!',
  'no_banners_available': 'No banners available',
  'skip': 'Skip',
  'get_started': 'Get Started',
  'next': 'Next',
  'select_language': 'Select Language',
  'toggle_theme': 'Toggle Theme',
  'education_for_everyone': 'Education For Everyone',
  'empowering_minds':
      'Empowering Minds, Building a Better Bangladesh\nLearn for Free!',
  'learn_and_share': 'Learn and Share',
  'learn_teach_inspire':
      'Learn, Teach, and Inspire Together, We Create Change!',
  'transform_the_future': 'Transform the Future',
  'knowledge_our_progress':
      'Your Knowledge, Our Progress Shaping a New Bangladesh!',
  'no_user_profile_found': 'No user profile found',
  'about_user': 'About User',
  'notification': 'Notification',
  'help_center': 'Help Center',
  'invite_friends': 'Invite Friends',
};
